spring:

  data:
    mongodb:
      database: instaclone_auth

  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
          configuration:
              key:
                serializer: org.apache.kafka.common.serialization.StringSerializer
      bindings:
        momentsUserChanged:
          destination: moments.user.changed
          contentType: application/json

server:
  port: 8080
      
security:
  basic:
    enable: false

  jwt:
    secret: JwtSecretKey
  service:
    username: ef919ae4-b893-4969-b782-57978180ad33
    password: d245ef53-5ad5-4216-9c56-89fe0f8302a0