apiVersion: v1
kind: Secret
metadata:
  name: insta-secrets
type: Opaque
data:
  security.jwt.secret: Snd0U2VjcmV0S2V5
  security.service.username: ZDI0NWVmNTMtNWFkNS00MjE2LTljNTYtODlmZTBmODMwMmEw
  security.service.password: ZWY5MTlhZTQtYjg5My00OTY5LWI3ODItNTc5NzgxODBhZDMz