
spring:
  application:
    name: insta-notification

  data:
    mongodb:
      database: instaclone_notifications

  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
          configuration:
            key:
              deserializer: org.apache.kafka.common.serialization.StringDeserializer
        bindings:
          momentsNotifications:
            consumer:
              startOffset: latest
              autoCommitOffset: false
      bindings:
        momentsNotifications:
          destination: moments.notifications
          contentType: application/json
          group: notificationService
          consumer:
            startOffset: latest
            autoCommitOffset: false

server:
  port: 8004

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

security:
  basic:
    enable: false

  jwt:
    uri: /auth/**
    header: Authorization
    prefix: Bearer
    expiration: 86400
    secret: JwtSecretKey